# Generated by Django 3.2.5 on 2021-07-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
