# Generated by Django 3.2.5 on 2021-07-13 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_alter_data_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Job',
        ),
    ]
