# Generated by Django 3.2.5 on 2021-07-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('nombre_integrante', models.CharField(max_length=255)),
                ('id_integrante', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_linea', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('integrante', models.ManyToManyField(blank=True, to='lineasinvestigacionApp.Integrante')),
            ],
        ),
    ]
