# Generated by Django 3.2.5 on 2021-07-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivos',
            new_name='Archivo',
        ),
    ]
