# Generated by Django 3.2.5 on 2021-07-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0003_auto_20210716_1108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.RemoveField(
            model_name='lineainvestigacion',
            name='integrante',
        ),
        migrations.DeleteModel(
            name='Integrante',
        ),
        migrations.DeleteModel(
            name='LineaInvestigacion',
        ),
    ]
