# Generated by Django 3.2.5 on 2021-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0007_archivo_integrante_lineainvestigacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='url_archivo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
