# Generated by Django 3.2.5 on 2021-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0008_archivo_url_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='archivo',
            field=models.ManyToManyField(blank=True, to='lineasinvestigacionApp.Archivo'),
        ),
    ]
