# Generated by Django 3.2.5 on 2021-07-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0009_lineainvestigacion_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='url_archivo',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
