# Generated by Django 3.2.5 on 2021-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0011_auto_20210720_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Produccion',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='id_proyecto',
            new_name='id_produccion',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='nombre_proyecto',
            new_name='nombre_produccion',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='url_proyecto',
            new_name='url_produccion',
        ),
        migrations.RemoveField(
            model_name='lineainvestigacion',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='lineainvestigacion',
            name='produccion',
            field=models.ManyToManyField(blank=True, to='lineasinvestigacionApp.Produccion'),
        ),
    ]
