# Generated by Django 3.2.5 on 2021-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0013_auto_20210720_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='categoría_archivo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='datamod_archivo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='descripcion_archivo',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='informacion_contacto',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='licencia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archivo',
            name='palabras_clave',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
