# Generated by Django 3.2.5 on 2021-07-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0014_auto_20210721_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='producto_asociado',
            field=models.ManyToManyField(blank=True, to='lineasinvestigacionApp.Producto'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='categoría_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='datamod_archivo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='descripcion_archivo',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='informacion_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='palabras_clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='url_archivo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
