# Generated by Django 3.2.5 on 2021-07-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0015_auto_20210722_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='visibilidad',
            field=models.CharField(choices=[('publico', 'publico'), ('privado', 'privado')], default='privado', max_length=10),
        ),
    ]
