# Generated by Django 3.2.5 on 2021-07-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0016_lineainvestigacion_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='formato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
