# Generated by Django 3.2.5 on 2021-08-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0017_archivo_formato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='categoría_archivo',
            new_name='categoria_archivo',
        ),
    ]
