# Generated by Django 3.2.5 on 2021-08-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0018_rename_categoría_archivo_archivo_categoria_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='categoria_archivo',
            field=models.CharField(choices=[('EP', 'Ensamblaje de proteínas'), ('BD', 'Bases de datos'), ('E', 'Estadística')], max_length=10),
        ),
    ]
