# Generated by Django 3.2.5 on 2021-08-03 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0022_alter_archivo_categoria_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='categoria_archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='categoria_archivo',
            field=models.ManyToManyField(blank=True, choices=[('BD', 'Bases de datos'), ('E', 'Estadística'), ('EP', 'Ensamblaje de proteínas')], max_length=500, null=True, to='lineasinvestigacionApp.Categoria'),
        ),
    ]
