# Generated by Django 3.2.5 on 2021-08-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0025_auto_20210803_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='categoria_archivo',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
