# Generated by Django 3.2.5 on 2021-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0027_auto_20210803_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineainvestigacion',
            name='img_header',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
