# Generated by Django 3.2.5 on 2021-08-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0028_lineainvestigacion_img_header'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineainvestigacion',
            old_name='img_header',
            new_name='imgheader',
        ),
    ]
