# Generated by Django 3.2.5 on 2021-08-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0029_rename_img_header_lineainvestigacion_imgheader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivo',
            old_name='pub_date',
            new_name='fecha',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='datamod_archivo',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
