# Generated by Django 3.2.5 on 2021-09-21 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lineasinvestigacionApp', '0031_alter_lineainvestigacion_visibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[(1, 'Jefe'), (2, 'Técnico'), (3, 'Admin')], max_length=10)),
                ('id_linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_linea_permiso', to='lineasinvestigacionApp.lineainvestigacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
