# Generated by Django 3.2.5 on 2021-09-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0032_auto_20210921_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='permiso',
            field=models.CharField(choices=[('Jefe', 'Jefe'), ('Técnico', 'Técnico'), ('Admin', 'Admin')], max_length=10),
        ),
    ]
