# Generated by Django 3.2.5 on 2021-09-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineasinvestigacionApp', '0033_alter_permiso_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='id_linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_permiso', to='lineasinvestigacionApp.lineainvestigacion'),
        ),
    ]
